experimental:
  plugins:
    bouncer:
      moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: v1.4.1
    htransformation:
      moduleName: "github.com/tomMoulard/htransformation"
      version: "v0.3.3"

accessLog: 
  filePath: "/logs/traefik.log"
  format: json
  fields:
    defaultMode: drop
    names:
      ClientAddr: keep
      User-Agent: keep

providers:
  file:
    filename: /etc/traefik/dynamic.yml
entrypoints:
  web:
    address: :80

