services:
  traefik:
    image: traefik:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - "./traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./dynamic.yml:/etc/traefik/dynamic.yml:ro"
    network_mode: "slirp4netns:port_handler=slirp4netns"

