experimental:
  plugins:
    htransformation:
      moduleName: "github.com/tomMoulard/htransformation"
      version: "v0.3.3"

accessLog: 
  format: json
  fields:
    defaultMode: keep
    headers:
      defaultMode: keep
    names:
      ClientAddr: keep

log:
  level: TRACE
providers:
  file:
    filename: /etc/traefik/dynamic.yml
entrypoints:
  web:
    address: :80

